version: "3"
services:
  rabbitmq-dev:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq-dev"
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      - "RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log [{console,[{level,debug}]}]"
